# Generated by Django 5.0.4 on 2024-04-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ddate',
            new_name='date',
        ),
    ]
